/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication5;

import javax.swing.JRootPane;
import javax.swing.WindowConstants;

/**
 *
 * @author User-PC
 */
public class AdvanceSearchingSKel extends javax.swing.JFrame {
    
    public AdvanceSearchingSKel() {
        initComponents();
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);        
        setResizable(false);
        MonthComboBox2.setSelectedItem(ABORT);
    }
    
    public Object[] getKomponen(){
        Object[] o = new Object[4];
        if(MonthComboBox.getSelectedItem() != "None")
        o[0] = MonthComboBox.getSelectedItem();
        else
        o[0] = "___";                            
        
        if(YearComboBox.getSelectedItem() != "None")
        o[1] = YearComboBox.getSelectedItem();
        else
        o[1] = "____";        
        return o;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MonthComboBox2 = new javax.swing.JComboBox<>();
        YearComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MonthComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        YearComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Search = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        DeleteSearchBTN = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        MonthComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        YearComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        MonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des" }));
        MonthComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MonthComboBoxItemStateChanged(evt);
            }
        });

        jLabel1.setText("Pilih Bulan         :");

        jLabel2.setText("Pilih Tahun       :");

        YearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "2018", "2019", "2020", "2021", "2022", "2023" }));
        YearComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                YearComboBoxItemStateChanged(evt);
            }
        });

        jLabel3.setText("Tanggal Surat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MonthComboBox, 0, 70, Short.MAX_VALUE)
                    .addComponent(YearComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(YearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Search.setText("Tutup");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        DeleteSearchBTN.setText("Delete Pencarian");
        DeleteSearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSearchBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteSearchBTN)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search)
                    .addComponent(Reset)
                    .addComponent(DeleteSearchBTN))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PENCARIAN LANJUTAN DATA SURAT KELUAR");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel5)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("SuspiciousIndentAfterControlStatement")
    private void MonthComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MonthComboBoxItemStateChanged
        if(MonthComboBox.getSelectedItem() == "None")
        MonthComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        else if(MonthComboBox.getSelectedItem() == "Jan")
        MonthComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan","Feb","Mar","Apr","Mei","Jun","Jul","Agu","Sep","Okt","Nov","Des" }));
        else if(MonthComboBox.getSelectedItem() == "Feb")
        MonthComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feb","Mar","Apr","Mei","Jun","Jul","Agu","Sep","Okt","Nov","Des" }));
        else if(MonthComboBox.getSelectedItem() == "Mar")
        MonthComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mar","Apr","Mei","Jun","Jul","Agu","Sep","Okt","Nov","Des" }));
        else if(MonthComboBox.getSelectedItem() == "Apr")
        MonthComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apr","Mei","Jun","Jul","Agu","Sep","Okt","Nov","Des" }));
        else if(MonthComboBox.getSelectedItem() == "Mei")
        MonthComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mei","Jun","Jul","Agu","Sep","Okt","Nov","Des" }));
        else if(MonthComboBox.getSelectedItem() == "Jun")
        MonthComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jun","Jul","Agu","Sep","Okt","Nov","Des" }));
        else if(MonthComboBox.getSelectedItem() == "Jul")
        MonthComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jul","Agu","Sep","Okt","Nov","Des" }));
        else if(MonthComboBox.getSelectedItem() == "Agu")
        MonthComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agu","Sep","Okt","Nov","Des" }));
        else if(MonthComboBox.getSelectedItem() == "Sep")
        MonthComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sep","Okt","Nov","Des" }));
        else if(MonthComboBox.getSelectedItem() == "Okt")
        MonthComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Okt","Nov","Des" }));
        else if(MonthComboBox.getSelectedItem() == "Nov")
        MonthComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nov","Des" }));
        else if(MonthComboBox.getSelectedItem() == "Des")
        MonthComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Des" }));
        
    }//GEN-LAST:event_MonthComboBoxItemStateChanged

    private void YearComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_YearComboBoxItemStateChanged
        if(YearComboBox.getSelectedItem() == "None")
        YearComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        if(YearComboBox.getSelectedItem() == "2018")
        YearComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018","2019","2020","2021","2022","2023" }));
        else if(YearComboBox.getSelectedItem() == "2019")
        YearComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019","2020","2021","2022","2023" }));
        else if(YearComboBox.getSelectedItem() == "2020")
        YearComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020","2021","2022","2023" }));
        else if(YearComboBox.getSelectedItem() == "2021")
        YearComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021","2022","2023" }));
        else if(YearComboBox.getSelectedItem() == "2022")
        YearComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022","2023" }));
        else if(YearComboBox.getSelectedItem() == "2023")
        YearComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023" }));        
    }//GEN-LAST:event_YearComboBoxItemStateChanged

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        MonthComboBox.setSelectedItem("None");
        YearComboBox.setSelectedItem("None");           
    }//GEN-LAST:event_ResetActionPerformed

    private void DeleteSearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSearchBTNActionPerformed
        Suratkeluar.AdvSearch = false;
        MonthComboBox.setSelectedItem("None");
        YearComboBox.setSelectedItem("None");        
        this.setVisible(false);
    }//GEN-LAST:event_DeleteSearchBTNActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        this.setVisible(false);        
    }//GEN-LAST:event_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvanceSearchingSKel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdvanceSearchingSKel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteSearchBTN;
    private javax.swing.JComboBox<String> MonthComboBox;
    private javax.swing.JComboBox<String> MonthComboBox2;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Search;
    private javax.swing.JComboBox<String> YearComboBox;
    private javax.swing.JComboBox<String> YearComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
